version: '3.8'

name: dokku_node_app_example

services:
  mongo:
    image: mongo:4
    networks:
      - web
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  
  app:
    build: ./
    networks:
      - web
    ports:
      - 8500:5000
    environment:
      PORT: 5000
      MONGO_URL: "mongodb://mongo:27017/users"

networks:
  web:

volumes:
  mongo-data: